name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  CI: true
  NODE_ENV: test
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Restore Yarn cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install dependencies
        run: |
          yarn config set enableGlobalCache false
          yarn --immutable

      - name: Save Yarn cache
        if: ${{ steps.restore-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: .yarn/cache
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Linting
        run: |
          yarn lint

      - name: Check types
        run: yarn test:types

      - name: Build
        run: yarn build

      - name: Setup for deploy
        if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.node == 20 }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm whoami

      - name: Publish to npm
        if: ${{ startsWith(github.ref, 'refs/tags/v') && matrix.node == 20 }}
        run: npm publish
